"use client";

import Image from "next/image";
import { FadeIn } from "@/components/FadeIn";
import { Nav } from "@/components/Nav";
import { experience, skillGroups, summary } from "@/data/resume";

function SectionHeading({ id, eyebrow, title }: { id: string; eyebrow: string; title: string }) {
  return <div id={id} className="mb-8 scroll-mt-24"><p className="mb-2 text-xs font-semibold uppercase tracking-[0.18em] text-teal-700">{eyebrow}</p><h2 className="text-2xl font-semibold tracking-tight text-stone-900 sm:text-3xl">{title}</h2></div>;
}

const cardClass = "rounded-2xl border border-stone-200 bg-white shadow-[0_12px_36px_rgba(28,25,23,0.06)]";

export default function Home() {
  return <div id="top" className="min-h-screen overflow-x-hidden bg-stone-50"><Nav /><main className="mx-auto max-w-5xl px-5 pb-20 pt-12 sm:px-6 sm:pt-16">
    <FadeIn><section className="mb-20"><p className="mb-3 text-sm font-medium text-teal-700">Edmonton, AB · Open to remote / WFH</p><h1 className="max-w-3xl text-4xl font-semibold tracking-tight text-stone-900 sm:text-5xl lg:text-6xl">Gio Franz Magracia</h1><p className="mt-4 max-w-2xl text-lg text-slate-700 sm:text-xl">Engineer-in-Training (APEGA) <span className="text-stone-400">|</span> Project Manager <span className="text-stone-400">|</span> PMP Eligible</p><p className="mt-6 max-w-3xl text-base leading-relaxed text-slate-600 sm:text-[1.05rem]">{summary}</p><div className="mt-8 flex flex-wrap gap-3"><a href="mailto:giomagracia@gmail.com" className="rounded-full bg-teal-700 px-5 py-2.5 text-sm font-semibold text-white shadow-lg shadow-teal-900/10 transition hover:bg-teal-800">Email me</a><a href="tel:3068077167" className="rounded-full border border-stone-300 bg-white px-5 py-2.5 text-sm font-medium text-stone-800 transition hover:border-teal-700/50 hover:text-teal-800">306-807-7167</a><a href="https://www.linkedin.com/in/giofranzmagracia" target="_blank" rel="noopener noreferrer" className="rounded-full border border-stone-300 bg-white px-5 py-2.5 text-sm font-medium text-stone-800 transition hover:border-teal-700/50 hover:text-teal-800">LinkedIn</a></div><div className="relative mt-10 overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-[0_16px_42px_rgba(28,25,23,0.08)]"><Image src="/images/hero-banner.png" alt="Abstract construction leadership and calm technology illustration" width={1280} height={720} priority className="h-auto w-full object-cover" sizes="(max-width: 1024px) 100vw, 1024px" /></div></section></FadeIn>
    <FadeIn><section className="mb-16"><p className="mb-4 text-xs font-semibold uppercase tracking-[0.18em] text-teal-700">Ventures</p><div className="grid gap-5 sm:grid-cols-2"><a href="#experience" className={`${cardClass} group overflow-hidden transition hover:-translate-y-0.5 hover:border-teal-700/40`}><div className="relative aspect-[16/9] overflow-hidden bg-stone-100"><Image src="/images/code-ninjas-education.png" alt="Bright STEM and coding learning space" fill className="object-cover transition duration-500 group-hover:scale-[1.03]" sizes="(max-width: 640px) 100vw, 50vw" /></div><div className="p-5"><p className="text-sm font-semibold text-stone-900">Code Ninjas Central Edmonton</p><p className="mt-1 text-xs text-slate-500">Cofounder, Owner & Operator · Present</p></div></a><a href="#experience" className={`${cardClass} group overflow-hidden transition hover:-translate-y-0.5 hover:border-teal-700/40`}><div className="relative aspect-[16/9] overflow-hidden bg-stone-100"><Image src="/images/maintello-ai.png" alt="Calm dashboards and AI implementation workflows" fill className="object-cover transition duration-500 group-hover:scale-[1.03]" sizes="(max-width: 640px) 100vw, 50vw" /></div><div className="p-5"><p className="text-sm font-semibold text-stone-900">Maintello</p><p className="mt-1 text-xs text-slate-500">Founder · 2026 – Present</p></div></a></div></section></FadeIn>
    <section className="mb-20"><FadeIn><SectionHeading id="experience" eyebrow="Career" title="Experience" /></FadeIn><div className="space-y-6">{experience.map((role, i) => <FadeIn key={`${role.company}-${role.dates}`} delay={i * 0.06}><article className={`${cardClass} overflow-hidden`}>{role.image ? <div className="relative aspect-[21/9] w-full overflow-hidden border-b border-stone-200 bg-stone-100 sm:aspect-[24/9]"><Image src={role.image} alt={role.imageAlt || `${role.company} illustration`} fill className="object-cover" sizes="(max-width: 1024px) 100vw, 1024px" /></div> : null}<div className="p-6 sm:p-7"><div className="flex flex-col gap-1 sm:flex-row sm:items-baseline sm:justify-between sm:gap-4"><div><h3 className="text-lg font-semibold text-stone-900">{role.title}</h3><p className="text-teal-800">{role.company}</p>{role.location ? <p className="mt-1 text-xs text-slate-500">{role.location}</p> : null}{role.company === "Code Ninjas Central Edmonton" ? <a href="https://www.codeninjas.com/central-edmonton-ab-ca" target="_blank" rel="noopener noreferrer" className="mt-2 inline-block text-xs font-medium text-teal-700 underline decoration-teal-700/30 underline-offset-4 hover:text-teal-900">Center information</a> : null}</div><p className="shrink-0 text-sm font-medium text-slate-500">{role.dates}</p></div><ul className="mt-5 space-y-2.5">{role.bullets.map((b) => <li key={b.slice(0, 48)} className="flex gap-3 text-sm leading-relaxed text-slate-600 sm:text-[0.95rem]"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-teal-700/70" aria-hidden /><span>{b}</span></li>)}</ul></div></article></FadeIn>)}</div></section>
    <section className="mb-20"><FadeIn><SectionHeading id="education" eyebrow="Credentials" title="Education & Certifications" /></FadeIn><div className="grid gap-5 md:grid-cols-2"><FadeIn delay={0.05}><div className={`${cardClass} h-full p-6`}><h3 className="text-sm font-semibold uppercase tracking-wider text-slate-500">Education</h3><p className="mt-3 text-lg font-semibold text-stone-900">B.A.Sc., Petroleum Engineering (Co-op Program)</p><p className="mt-1 text-teal-800">University of Regina</p></div></FadeIn><FadeIn delay={0.1}><div className={`${cardClass} h-full p-6`}><h3 className="text-sm font-semibold uppercase tracking-wider text-slate-500">Certifications & Memberships</h3><ul className="mt-3 space-y-2 text-[0.95rem] leading-relaxed text-slate-600"><li>Engineer-in-Training — Association of Professional Engineers and Geoscientists of Alberta (APEGA)</li><li>PMP Eligible (not yet certified)</li></ul></div></FadeIn></div></section>
    <section className="mb-20"><FadeIn><SectionHeading id="skills" eyebrow="Capabilities" title="Skills" /></FadeIn><div className="grid gap-5 md:grid-cols-3">{skillGroups.map((group, i) => <FadeIn key={group.label} delay={i * 0.06}><div className={`${cardClass} h-full p-6`}><h3 className="text-sm font-semibold uppercase tracking-wider text-teal-800">{group.label}</h3><div className="mt-4 flex flex-wrap gap-2">{group.items.map((item) => <span key={item} className="rounded-full border border-stone-200 bg-stone-50 px-3 py-1 text-xs text-slate-600">{item}</span>)}</div></div></FadeIn>)}</div></section>
    <section className="mb-20"><FadeIn><div className="grid gap-5 sm:grid-cols-3"><div className={`${cardClass} p-5`}><h3 className="text-sm font-semibold text-teal-800">Select recognition</h3><p className="mt-2 text-sm leading-relaxed text-slate-600">“You See It You Own It” campaign — top candidate recognition</p></div><div className={`${cardClass} p-5`}><h3 className="text-sm font-semibold text-teal-800">Volunteering</h3><p className="mt-2 text-sm leading-relaxed text-slate-600">Graham Indigenous Engagement — volunteer attendee, 2021 – 2022</p></div><div className={`${cardClass} p-5`}><h3 className="text-sm font-semibold text-teal-800">References</h3><p className="mt-2 text-sm leading-relaxed text-slate-600">Available upon request.</p></div></div></FadeIn></section>
    <FadeIn><section id="contact" className="scroll-mt-24 overflow-hidden rounded-3xl border border-teal-700/15 bg-teal-50/60 p-8 shadow-[0_16px_42px_rgba(53,107,109,0.08)] sm:p-10"><h2 className="text-2xl font-semibold text-stone-900 sm:text-3xl">Let’s connect</h2><p className="mt-3 max-w-xl text-slate-600">Open to remote / hybrid Project Manager roles. Reach out by email, phone, or LinkedIn.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row sm:flex-wrap"><a href="mailto:giomagracia@gmail.com" className="inline-flex items-center justify-center rounded-full bg-teal-700 px-6 py-3 text-sm font-semibold text-white transition hover:bg-teal-800">giomagracia@gmail.com</a><a href="tel:3068077167" className="inline-flex items-center justify-center rounded-full border border-stone-300 bg-white px-6 py-3 text-sm font-medium text-stone-800 transition hover:border-teal-700/50 hover:text-teal-800">306-807-7167</a><a href="https://www.linkedin.com/in/giofranzmagracia" target="_blank" rel="noopener noreferrer" className="inline-flex items-center justify-center rounded-full border border-stone-300 bg-white px-6 py-3 text-sm font-medium text-stone-800 transition hover:border-teal-700/50 hover:text-teal-800">linkedin.com/in/giofranzmagracia</a></div></section></FadeIn>
  </main><footer className="border-t border-stone-200 py-8 text-center text-sm text-slate-500"><p>© {new Date().getFullYear()} Gio Franz Magracia · <a href="https://www.linkedin.com/in/giofranzmagracia" target="_blank" rel="noopener noreferrer" className="text-slate-600 transition hover:text-teal-800">LinkedIn</a></p></footer></div>;
}
